volumes:
  {{project_name}}_backend_local_postgres_data: {}
  {{project_name}}_backend_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    container_name: {{project_name}}_backend_local_django
    volumes:
      - .:/app
    environment:
      # DJANGO SETTINGS
      - DJANGO_DEBUG=True
      - USE_DOCKER=yes
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - IPYTHONDIR=/app/.ipython
      # DB SETTINGS
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB={{project_name}}_db
      - POSTGRES_USER=debug
      - POSTGRES_PASSWORD=debug
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: local-webserver # Command located on entry production/django/entrypoint

  postgres:
    image: postgres:16
    container_name: {{project_name}}_backend_local_postgres
    restart: on-failure
    volumes:
      - {{project_name}}_backend_local_postgres_data:/var/lib/postgresql/data
      - {{project_name}}_backend_local_postgres_data_backups:/backups
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB={{project_name}}_db
      - POSTGRES_USER=debug
      - POSTGRES_PASSWORD=debug
    ports:
      - "5432:5432"
